const NAME_MIN_LENGTH = 1;
const NAME_MAX_LENGTH = 100;

const API_KEY_MIN_LENGTH = 32;
const API_KEY_MAX_LENGTH = 128;
const API_KEY_REGEX = /^[A-Za-z0-9_-]+$/;

export { NAME_MIN_LENGTH, NAME_MAX_LENGTH, API_KEY_MIN_LENGTH, API_KEY_MAX_LENGTH, API_KEY_REGEX };
