export const ENV = {
    MILVUS_ADDRESS: process.env.NEXT_PUBLIC_MILVUS_ADDRESS!,
    MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI!,
    UPSTASH_REDIS_URL: process.env.NEXT_PUBLIC_UPSTASH_REDIS_URL!,
    UPSTASH_REDIS_TOKEN: process.env.NEXT_PUBLIC_UPSTASH_REDIS_TOKEN!,
} as const;
